<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <AotWarningsToIgnore>IL2104;IL3000</AotWarningsToIgnore>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\TermRTS\TermRTS.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="ConsoleRenderer" Version="0.9.0" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.11"/>
        <PackageReference Include="Xdg.Directories" Version="0.2.0"/>
    </ItemGroup>

</Project>