using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using TermRTS.Ecs;
using TermRTS.Event;

namespace TermRTS.Serialization;

/// <summary>
///     Registers concrete game types that may appear in a persisted simulation state.
/// </summary>
public sealed class PersistenceTypeRegistry
{
    private readonly List<PersistenceTypeRegistration> _components = [];
    private readonly List<PersistenceEventRegistration> _events = [];

    public PersistenceTypeRegistry()
    {
        RegisterEvent("termrts.persist", GetTypeInfo<Persist>(TermRTSJsonContext.Default));
        RegisterEvent("termrts.shutdown", GetTypeInfo<Shutdown>(TermRTSJsonContext.Default));
        RegisterEvent("termrts.system-log", GetTypeInfo<SystemLog>(TermRTSJsonContext.Default));
        RegisterEvent("termrts.profile", GetTypeInfo<Profile>(TermRTSJsonContext.Default));
    }

    internal IReadOnlyList<PersistenceTypeRegistration> Components => _components;

    internal IReadOnlyList<PersistenceEventRegistration> Events => _events;

    /// <summary>
    ///     Registers a game component using metadata generated by a <see cref="JsonSerializerContext" />.
    /// </summary>
    public PersistenceTypeRegistry RegisterComponent<TComponent>(
        string discriminator,
        JsonSerializerContext context)
        where TComponent : ComponentBase
    {
        return RegisterComponent(discriminator, GetTypeInfo<TComponent>(context));
    }

    /// <summary>
    ///     Registers a game component using generated JSON metadata.
    /// </summary>
    public PersistenceTypeRegistry RegisterComponent<TComponent>(
        string discriminator,
        JsonTypeInfo<TComponent> typeInfo)
        where TComponent : ComponentBase
    {
        AddRegistration(_components, discriminator, typeInfo);
        return this;
    }

    /// <summary>
    ///     Registers an event payload using metadata generated by a <see cref="JsonSerializerContext" />.
    /// </summary>
    public PersistenceTypeRegistry RegisterEvent<TPayload>(
        string discriminator,
        JsonSerializerContext context)
    {
        return RegisterEvent(discriminator, GetTypeInfo<TPayload>(context));
    }

    /// <summary>
    ///     Registers an event payload using generated JSON metadata.
    /// </summary>
    public PersistenceTypeRegistry RegisterEvent<TPayload>(
        string discriminator,
        JsonTypeInfo<TPayload> typeInfo)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(discriminator);
        ArgumentNullException.ThrowIfNull(typeInfo);

        if (_events.Any(registration =>
                registration.Discriminator == discriminator ||
                registration.EventType == typeof(Event<TPayload>)))
        {
            throw new ArgumentException(
                $"A persistence registration already exists for discriminator '{discriminator}' or payload type '{typeof(TPayload)}'.",
                nameof(discriminator));
        }

        _events.Add(new PersistenceEventRegistration<TPayload>(discriminator, typeInfo));
        return this;
    }

    private static JsonTypeInfo<T> GetTypeInfo<T>(JsonSerializerContext context)
    {
        ArgumentNullException.ThrowIfNull(context);
        return context.GetTypeInfo(typeof(T)) as JsonTypeInfo<T>
               ?? throw new ArgumentException(
                   $"The supplied JSON context does not contain generated metadata for {typeof(T)}.",
                   nameof(context));
    }

    private static void AddRegistration<T>(
        ICollection<PersistenceTypeRegistration> registrations,
        string discriminator,
        JsonTypeInfo<T> typeInfo)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(discriminator);
        ArgumentNullException.ThrowIfNull(typeInfo);

        if (registrations.Any(registration =>
                registration.Discriminator == discriminator ||
                registration.TypeInfo.Type == typeInfo.Type))
        {
            throw new ArgumentException(
                $"A persistence registration already exists for discriminator '{discriminator}' or type '{typeInfo.Type}'.",
                nameof(discriminator));
        }

        registrations.Add(new PersistenceTypeRegistration(discriminator, typeInfo));
    }
}

internal sealed record PersistenceTypeRegistration(string Discriminator, JsonTypeInfo TypeInfo);

internal abstract record PersistenceEventRegistration(string Discriminator, Type EventType)
{
    public abstract IEvent Read(JsonElement value, ulong triggerTime);

    public abstract void Write(Utf8JsonWriter writer, IEvent value);
}

internal sealed record PersistenceEventRegistration<TPayload>(
    string Discriminator,
    JsonTypeInfo<TPayload> TypeInfo)
    : PersistenceEventRegistration(Discriminator, typeof(Event<TPayload>))
{
    public override IEvent Read(JsonElement value, ulong triggerTime)
    {
        var payload = JsonSerializer.Deserialize(value.GetRawText(), TypeInfo);
        return new Event<TPayload>(payload!, triggerTime);
    }

    public override void Write(Utf8JsonWriter writer, IEvent value)
    {
        if (value is not Event<TPayload> eventValue)
        {
            throw new JsonException(
                $"Registered event type '{EventType}' does not match value type '{value.GetType()}'.");
        }

        writer.WriteStartObject();
        writer.WriteString("$type", Discriminator);
        writer.WritePropertyName("$value");
        JsonSerializer.Serialize(writer, eventValue.Payload, TypeInfo);
        writer.WriteNumber("TriggerTime", eventValue.TriggerTime);
        writer.WriteEndObject();
    }
}